export const HOMEROUTE = "/" 
export const ADDPROJECTSROUTE = "/addproject" 
export const FAVOURITESROUTE = "/favorites" 
export const SKILLSROUTE = "/skills" 
export const ADDSKILLROUTE = "/addskill"
export const SHOWPROJECTROUTE = "/projects/:id"